version: '2'

services:
    percpetion:
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        network_mode: "host"
        ipc: "host"
        volumes:
            - /tmp:/tmp
        environment:
            - DISPLAY=${DISPLAY}
        command: "--cid=111 --name=img.argb --width=1280 --height=720 --verbose --Bl0=115 --Bl1=100 --Bl2=30 --Bh0=145 --Bh1=255 --Bh2=200 --Yl0=10 --Yl1=40 --Yl2=46 --Yh0=34 --Yh1=255 --Yh2=200 --crop_up=430 --crop_down=570 --crop_up_min_cone_area=600 --crop_down_min_cone_area=1000 --max_unmatch_y=30"

#        command: "--cid=111 --name=img.argb --width=1280 --height=720 --verbose
#            --Bl0=115   --Bl1=100   --Bl2=30
#            --Bh0=145   --Bh1=255   --Bh2=200
#            --Yl0=10    --Yl1=40    --Yl2=46
#            --Yh0=34    --Yh1=255   --Yh2=200
#            --crop_up=430                   --crop_down=570
#            --crop_up_min_cone_area=600     --crop_down_min_cone_area=1000
#            --max_unmatch_y=30
#        "


